name: Deploy Angular App to Web Disk

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Clean WebDisk Target Directory
        env:
          WEBDISK_USERNAME: ${{ secrets.WEBDISK_USERNAME }}
          WEBDISK_PASSWORD: ${{ secrets.WEBDISK_PASSWORD }}
        run: |
          WEBDISK_URL="https://devcamp.online:2078"
          
          echo "🧹 Attempting to clean up WebDisk directory: $WEBDISK_URL"

          # List and delete files in the root (non-recursive)
          FILES=$(curl -k -s -u "$WEBDISK_USERNAME:$WEBDISK_PASSWORD" "$WEBDISK_URL" | grep -oP '(?<=<d:href>).*?(?=</d:href>)')

          for FILE in $FILES; do
            CLEANED_FILE=$(echo "$FILE" | sed 's|^/||')
            if [ "$CLEANED_FILE" != "" ] && [ "$CLEANED_FILE" != "/" ]; then
              echo "🗑️ Deleting: $WEBDISK_URL/$CLEANED_FILE"
              curl -k -s -S -u "$WEBDISK_USERNAME:$WEBDISK_PASSWORD" -X DELETE "$WEBDISK_URL/$CLEANED_FILE" || true
            fi
          done

      - name: Deploy via WebDAV
        env:
          WEBDISK_USERNAME: ${{ secrets.WEBDISK_USERNAME }}
          WEBDISK_PASSWORD: ${{ secrets.WEBDISK_PASSWORD }}
        run: |
          BUILD_DIR="dist/devops/browser"
          WEBDISK_URL="https://devcamp.online:2078"

          find "$BUILD_DIR" -type f | while read -r file; do
            RELATIVE_PATH="${file#"$BUILD_DIR/"}"
            REMOTE_PATH="${WEBDISK_URL}/${RELATIVE_PATH}"

            echo "Uploading $file to $REMOTE_PATH"

            # Create remote directory structure
            DIR_PATH=$(dirname "$RELATIVE_PATH")
            if [ "$DIR_PATH" != "." ]; then
              IFS='/' read -ra DIR_PARTS <<< "$DIR_PATH"
              PARTIAL_PATH=""
              for PART in "${DIR_PARTS[@]}"; do
                PARTIAL_PATH="$PARTIAL_PATH/$PART"
                curl -k -s -S -u "$WEBDISK_USERNAME:$WEBDISK_PASSWORD" -X MKCOL "${WEBDISK_URL}${PARTIAL_PATH}" || true
              done
            fi

            curl -k -s -S -u "$WEBDISK_USERNAME:$WEBDISK_PASSWORD" -T "$file" "$REMOTE_PATH"

            if [ $? -ne 0 ]; then
              echo "❌ Failed to upload: $file"
              exit 1
            else
              echo "✅ Uploaded: $file"
            fi
          done
